### ISSUE TITLE
[6.0.0.rc-3] "Only a ReactOwner can have refs" issue when used in a Modal component

### ISSUE THREAD

**Issue by reintroducing** [redux-form/redux-form#1354]
I'm trying to use redux-form in a component that is a modal.  The Modal (as is seemingly customary with React modals) is rendered using this technique (basically wrapping a component around the actual Modal content so that it renders in the body as opposed to where the component is created in the "flow"):

```
import React, {Component, PropTypes} from 'react';
import ReactDOM from 'react-dom';
import {Provider} from 'react-intl-redux';
import DOMUtils from 'utils/dom';
import {store} from 'store';

class RenderInBody extends Component {
    componentDidMount() {
        const {
            className
        } = this.props;

        this.container = document.createElement('div');

        if (className) {
            DOMUtils.addClass(this.container, className);
        }

        document.body.appendChild(this.container);

        this._renderLayer();
    }

    componentDidUpdate(prevProps, prevState) {
        this._renderLayer();
    }

    componentWillUnmount() {
        ReactDOM.unmountComponentAtNode(this.container);
        document.body.removeChild(this.container);
    }

    _renderLayer() {
        ReactDOM.render(
            <Provider store={store}>
                {this.props.children}
            </Provider>,
        this.container);
    }

    render() {
        return null;
    }
}

RenderInBody.propTypes = {
    className: PropTypes.string,
    children: PropTypes.element.isRequired
};

export default RenderInBody;
```

I'm seeing the following error as soon as I decorate a Form component in that modal with reduxForm:

```
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

In the stack trace I see that its coming from the _renderLayer() method of RenderInBody and I imagine its because the modal is actually being rendered not in the render() method of that component but using `ReactDOM.render` and thus there is some place in reduxForm where a ref is being created which causes this error.  

Before decorating my Form with reduxForm everything was working correctly and I haven't even begun to define Fields or anything other than the decoration.  I think this is a pretty common use case for a form (opening it in a modal, say, a login form for example) and I'm kind of surprised nobody else has run into this previously.  

Am I doing something wrong or is this a real issue with redux-form?

**Comment by clindsey** [comment]
I'm running into this issue now also; when using ReactDOM to add a modal to the body and it has a decorated redux-form child, I see this error.  I haven't been able to find any solutions yet.

**Comment by clindsey** [comment]
**follow-up**: the only solution I can get working is to not use ReactDOM for the modal.  I was originally using the https://github.com/tajo/react-portal library and it does a great job of keeping the modal's content out of the DOM when the modal is hidden, but the decorated redux-form components are the `refs` errors issue.  Now my modal always lives at the root of the app's content and I use css to hide it.  It's not an ideal solution

**Comment by GaryChangCN** [comment]
delete node_modules/* then npm install

**Comment by michaelryancaputo** [comment]
@GaryChangCN I'm having a similar problem here, and as your comment says to delete the node_modules folder - it fixes the issue, however, our production env caches npm packages aggressively and this isn't an option. Any idea _why_ this fixes it?

**Comment by mattkrick** [comment]
still a thing in 7.0.3. rimrafing node_modules works beautifully!

**Comment by iamandrewluca** [comment]
Does someone still has this issue in v6?
If rimrafing `node_modules` solves this issue, then the problem may be in another part.
Didn't see any code example explicitly related to how `redux-form` is used.

If issue still persist, feel free to reopen it.
