### ISSUE TITLE
Validate with redux-form/immutable is returning literal objects instead of Immutable.Map

### ISSUE THREAD

**Issue by filipposarzana** [redux-form/redux-form#3532]
### What is the current behavior?
Using `redux-form/immutable` and `validate` on either `Form` or `field-level` errors are returned as literal objects

### What is the expected behavior?
Using `redux-form/immutable` and `validate` on either `Form` or `field-level` I expect them to be `Immutable.Map`.
In AsyncValidate errors are as a matter of fact `Immutable.Map`

### What's your environment?
Redux `v7.1.1`
All OS
Node `v8`

**Comment by davidowens** [comment]
I had this problem too - seems the docs and the examples are out of sync.

Take a look at this https://github.com/erikras/redux-form/blob/master/examples/immutable/src/ImmutableForm.js

I refactored around this example and it works as expected now

**Comment by filipposarzana** [comment]
@davidowens Unfortunately this is still not working since sync-validation and async-validation are returning different types:
sync -> `{}` object literal
async -> `Immutable.map`
