### ISSUE TITLE
[Question] Dismiss _error, but not field errors

### ISSUE THREAD

**Issue by inferusvv** [redux-form/redux-form#3537]
Hi. I have a form with validation on submit:

`<form onSubmit={handleSubmit(onSubmit)}>`

In validation I am doing this:

```
throw new SubmissionError({
  ...errors.list,
  _error: 'Please check all fields',
});
```

So in my form I have errors under each field and common error under all form. Can I hide **only** `_error` and keep all fields "red" when I start typing something in any form field?

**Comment by ingro** [comment]
I have a similar problem, I'm disabling the form's submission button if the form is `invalid`, but the form goes in invalid state not only for validation errors but also for form-level error. It will be nice to have a way to clear only form-level error!
