### ISSUE TITLE
null is equal to undefined and "". Custom deepEqual.

### ISSUE THREAD

**Issue by sanohin** [redux-form/redux-form#3796]
### Are you submitting a **bug report** or a **feature request**?

feature request, though in my case it is a bug

### What is the current behavior?

null and (undefined | "") are treated as equal 

### What is the expected behavior?
null and (undefined | "") should be treated as NOT equal.

### Sandbox Link

<https://q3xlpy475j.codesandbox.io/>

### What's your environment?

Redux-Form 7.2.1, does not depend on React/OS/browser/node version.

### Other information

It would be nice to have a possibility to provide own deepEqual, though something like comparing like `value == null` in `createFieldProps` when passing value to a component is also breaking (though this problem can be fixed with `format`)

**Comment by danielrob** [comment]
I don't understand your issue, your sandbox, or why you want this.
