### ISSUE TITLE
Missing flow typing in reducers

### ISSUE THREAD

**Issue by wouter-willems** [redux-form/redux-form#4000]
Hi,
I am using flow throughout my whole application, including reducers, actions etc.
I'd like to use the defined types from redux-forms as well. But in the docs I can only find information about Props, nothing about the store.
I tried finding clues in the code, but it doesnt seem to exist there either.

Is this planned for the near feature? I would love to know =)

**Comment by iamandrewluca** [comment]
@wouter-willems What flow types are you missing? What is your version?

**Comment by wouter-willems** [comment]
This is outdated, but thank you for the reply!
