### ISSUE TITLE
SubmissionErrors are ignored if not imported just right

### ISSUE THREAD

**Issue by ah-adarlow** [redux-form/redux-form#4092]
**feature request**

### What is the current behavior?
Currently, if the code throwing a SubmissionError imported a different copy of it (e.g. from root, immutable, or lib) than the copy of reduxForm being used, the errors are ignored.

[This sandbox](https://codesandbox.io/s/38xlnx6o06) demonstrates by changing the submit validation demo to import 'redux-form/lib/SubmissionError'. Note that errors will no longer show up after submitting.

### What is the expected behavior?
Ideally, you could trigger any copy of SubmissionError and have it work the same. This is especially desirable for libraries built on top of redux-form because they don't control their consumers' code.

### Sandbox Link
https://codesandbox.io/s/38xlnx6o06

### Cause and proposed solution
The reason this happens is because handleSubmit checks `submitError instanceof SubmissionError` and this fails if they're not looking at the same copy. I propose replacing all of these with `(submitError && submitError.name === 'SubmissionError')`.

### Other information
Related issues:
* https://github.com/erikras/redux-form/issues/2269
* https://github.com/Limenius/liform-react/issues/45

I also did a quick search for other uses of `instanceof` in redux-form and didn't find anything else problematic in this way.

**Comment by danielrob** [comment]
Thanks @ah-adarlow. Would you be comfortable to raise a PR for this? Sounds good to me.

**Comment by ah-adarlow** [comment]
PR: #4100

**Comment by thomasbertet** [comment]
Hi there, I see this issue is open but the PR is merged and landed in stable release. 
I came across an issue today where in my production bundle `submitError.name === 'SubmissionError'` does not work because `submitError.name` gets obfuscated and its value is a simple char. 

Do you ever encountered this ? I believe my webpack config might have something to do with this but not sure how to solve this anyhow.

With the old behavior, it was working fine. 

Thanks for your help :)

**Comment by ah-adarlow** [comment]
Ugh, I didn't think of obfuscation. Can you configure webpack not to obfuscate certain strings?

One longer-term solution would be to add an explicit isSubmissionError field to SubmissionError that's always set to true.

**Comment by thomasbertet** [comment]
> Ugh, I didn't think of obfuscation. Can you configure webpack not to obfuscate certain strings? 
Yeah I could but seems a bit hacky... seems weird to me nobody have seen this bug already.
May I submit a PR switching this behavior to a boolean like you described ?

**Comment by thomasbertet** [comment]
Oh I found https://github.com/erikras/redux-form/issues/4302#issuecomment-448998142 which is it.
It's fixed in 8.1.0 :)

**Comment by ah-adarlow** [comment]
I'm worried that the fix in 8.1.0 might re-introduce this issue for projects that package redux-form separately from the application code and minify one or both. I still think having an explicit boolean prop to check would be preferable.

**Comment by andreme** [comment]
@ah-adarlow I agree that an explicit flag would be better. I would like to throw an error that behaves like a SubmissionError, without having to actually require the redux-form module.

**Comment by vaibhav-systango** [comment]
@erikras @danielrob @andreme can someone help me? I'm using :
throw new SubmissionError({"error_key": "error_string"}) but still the error doesn't appears on the fields.
`      .catch((error) => {
          const response = error.response
          const data = response.data
          const code = response.status
          const errors = data?.errors ?? {}
          if (code >= 400 && code < 500 && Object.keys(errors).length > 0) {
            setCanContinue(false)
            const sanitised = Object.entries(errors).map(([k, v]) => [k[0].toUpperCase () + k.slice(1), v])
            throw new SubmissionError(Object.fromEntries(sanitised))
          }
          setApiError(data.title || GENERIC_ERROR_MESSAGE)
        })`

and here's my input field component:

`
import React from 'react'
import { FormGroup, Label, Input } from 'reactstrap'
import PropTypes from 'prop-types'
import { CustomForm } from './style'

const InputField = props => {
  const {
    input,
    label,
    type,
    name,
    id,
    disabled,
    inputMode,
    maxLength,
    pattern,
    meta: { touched, error, dirty },
    help,
    errorMessage,
    placeholder,
    className,
    showError,
  } = props
  return (
    <CustomForm>
      <FormGroup>
        <Label for={label}>{label}</Label>
        <Input
          {...input}
          type={type}
          name={name}
          id={id}
          placeholder={placeholder}
          className={
            showError && touched && dirty && error
              ? `error-input ${className || ''}`
              : `${className || ''}`
          }
          disabled={disabled || false}
          inputMode={inputMode}
          maxLength={maxLength}
          pattern={pattern}
        />
        {showError && touched && dirty && error && (
          <span className="error">{error}</span>
        )}
        {showError && !error && dirty && errorMessage && (
          <span className="error">{errorMessage}</span>
        )}
        {!error && help && <span className="helptext">{help}</span>}
      </FormGroup>
    </CustomForm>
  )
}

InputField.propTypes = {
  input: PropTypes.object,
  label: PropTypes.string,
  type: PropTypes.string,
  name: PropTypes.string,
  id: PropTypes.string,
  meta: PropTypes.object,
  help: PropTypes.string,
  placeholder: PropTypes.string,
  errorMessage: PropTypes.oneOfType([PropTypes.string, PropTypes.bool]),
  className: PropTypes.string,
  showError: PropTypes.bool,
  disabled: PropTypes.bool,
  inputMode: PropTypes.string,
  maxLength: PropTypes.string,
  pattern: PropTypes.string,
}

export default InputField
`

here's form component:
`          <Field
                    name={ "field_name"}
                    component={renderTextField}
                    label="What is your field name?"
                    id={"field_name"}
                    className="mbt-0"
                    showError={true}
                    validate={[lengthEquals(13), isValid("field_name")]}
                    inputMode="number"
                    minLength="13"
                    maxLength="13"
                    normalize={(value, previousValue) =>
                        decimalFormatter(value, previousValue, 0)
                    }
                    required
                />`

**Comment by iamandrewluca** [comment]
@vaibhav-systango please reformat your message.

**Comment by iamandrewluca** [comment]
Fixed in https://github.com/redux-form/redux-form/releases/tag/v8.3.4

**Comment by tronza** [comment]
> Fixed in https://github.com/redux-form/redux-form/releases/tag/v8.3.4

For those who are wondering why there might be weird constructor related errors after updating. This changes the import from `import SubmissionError from 'redux-form/lib/SubmissionError'` to `import { SubmissionError } from 'redux-form/lib/SubmissionError'`.
