### ISSUE TITLE
formValues not updating in nested form

### ISSUE THREAD

**Issue by tgreen7** [redux-form/redux-form#4137]
### Are you submitting a **bug report** or a **feature request**?
**bug report**
In the below sandbox you can see that I have a nested component which is wrapped with formValuesSelector and formValues. I have set a timeout that will change the initialvalues after 1 second. The value is properly updated with formValuesSelector but formValues does not get updated. This error only happens when passing a prop down to the form that is also changing.

### What is the current behavior?
https://codesandbox.io/s/q31q35o1rj

### What is the expected behavior?
That formValues will get the current value of the form

**Comment by tnrich** [comment]
I am also hitting the behavior described above and it is very confusing and a HUGE gotcha! There should be no reason for these two methods to perform so differently. 

`formValues()` is broken and needs to be fixed!

**Comment by tnrich** [comment]
This appears to be fixed in the latest versions of redux-form:

https://codesandbox.io/s/redux-form-formvalues-not-updating-forked-pu3l8
