### ISSUE TITLE
In Firefox a required input field is immediately styled as invalid

### ISSUE THREAD

**Issue by timdegroote** [redux-form/redux-form#4224]
### Are you submitting a **bug report** or a **feature request**?
A bug report.

### What is the current behavior?

In Firefox (v62.0.2) when setting the `required` attribute of a field, the input field is immediately styled as invalid. This behaviour is not reproducible in Chrome (69.0.3497.100) or Safari (12.0).

When inspected the input has the `:-moz-ui-invalid` psuedo-class applied (see https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-invalid).

### What is the expected behavior?

The input shouldn't be marked as invalid until the user has made a change to the field.

### Sandbox Link

This is basically the default sandbox, I simply passed `required` as a prop to the `Field` component.
https://codesandbox.io/s/43nwwy2j04

### What's your environment?

React 15.5.3
Redux 3.7.0
Redux-form 7.3.0
Firefox 62.0.2

**Comment by gustavohenke** [comment]
Tried to replicate this behaviour with pure HTML/JS. When setting the value to empty string, it happens.
Seems like Redux Form is manipulating the input in a way that triggers the invalid state...

**Comment by reiec** [comment]
Are you sure, that this is a problem of Redux Form? I think React has a problem here:
https://codesandbox.io/s/3q1xmzo70q
This template leads to the same error and does not use a Redux form.

**Comment by iamandrewluca** [comment]
As you mentioned the style is comming from a browser vendor and has nothing to do with `redux-form`

Try to add `<form noValidate>` to your form.

Closing this because is not related
