### ISSUE TITLE
Nested error is not highlighted

### ISSUE THREAD

**Issue by kailashvele** [redux-form/redux-form#4241]
when I submit the following structure error is not highlighted for attribute:

`{
    name: 'error for name',
    attributes.age: 'error for age'
}`

but when I throw the error with the following structure error is highlighted for both the keys:

`{
name: 'error for name',
attributes: {
   age: 'error for age'
}
}`

I suppose this was not the case earlier I do not remember which version I used at that time.

Sandbox:

https://codesandbox.io/s/6lz2765y53

Versions:
React: 16.2.0
Redux-form: 7.2.0
Chrome: 69.0.3497.100
MacOs: Mojave
Node: 10.11.0

**Comment by gustavohenke** [comment]
> I suppose this was not the case earlier

What do you mean by this? Is it that the `meta.error` for `attributes` didn't use to be set? Or is it that `attributes.age` used to work as a error key?


> I do not remember which version I used at that time.

It would help a lot to find the guilty commit if you could know the Redux Form version.

And finally...

> the following structure error is highlighted for both the keys

You are in control of the `attributes` field, so you can opt out of showing errors if you know the field has other fields inside it.
So it's fixable on your side.

**Comment by web2wire** [comment]
I believe I am seeing this as well.

My yup schema looks like this

```const schema = yup.object().shape({
  person_title:       yup.string().required().min(2).label("Title"),
  person_first_name:  yup.string().required().label("First Name"),
  person_last_name:   yup.string().required().label("Last Name"),
  person_email:       yup.string().email().required().label("Email"),
  person_phone:       yup.string().required().label("Phone"),
  person_mobile:      yup.string().nullable().label("Mobile"),
  home_address:       yup.object().required().shape({
    address_city:       yup.string().required().label("City"),
    address_country:    yup.string().required().label("Country"),
  }),
});
```
and the form fields for the address part are described thus

```
     <Form.Group>
        <Field component={FormInput} name="home_address.address_city" label="City" placeholder="City" width={6}/>
        <Field component={FormInput} name="home_address.address_postcode" label="Postcode" placeholder="Postcode" width={4}/>
        <Field component={FormInput} name="home_address.address_country" label="Country" placeholder="Country" width={6}/>
      </Form.Group>
```
When I omit country for example the error object return from validation is 

```{home_address.address_country: "Country is a required field"} ```

However no error flags are passed into the form component and the overall form is marked as valid.

Given that the error field path matches that of the field itself I would expect this to flag up an error in the field.

**Comment by iamandrewluca** [comment]
Right now `redux-form` does not support this.

```
{
  "name": "error for name",
  "attributes.age": "error for age"
}
```

Your returned errors should have this structure

```
{
  "name": "error for name",
  "attributes": {
    "age": "error for age"
  }
}
```

`redux-form` expects all data that gets into form, and gets out will be a object with key that are not dot–notation like.
