### ISSUE TITLE
How to determine if user tried to submit form?

### ISSUE THREAD

**Issue by Rendalf** [redux-form/redux-form#4316]
Right now it's pretty obvious how to figure out if user tried to submit form and redux-form started (and may be stopped) to submit form. But what if user clicked submit, but we interrupted them by async validation? Moreover, we should differ cases when user launched async validation by submit & by blur.

In other words, is there a way if we had failed async validation launched by attempt to submit form and not by blur event?

**Comment by zazapeta** [comment]
Hi,
Maybe I do not understand, but here is a suggestion : 
If the user can click on submit, then, we can assume that all fields are validated (or asyncValidated), isn't it ? Hence, you have to disable the submit if one is not valide.

Furthermore, the submit async function can throw a [SubmissionError](https://redux-form.com/8.2.2/docs/api/submissionerror.md/). Whereupon the form receives your 'errors'  and should display them as you want (if you want to bind them with their field, and thus, not manage how to display erros, you may throw `js  { field1: 'error', field2: 'error' }`).

**Comment by iamandrewluca** [comment]
https://redux-form.com/8.2.2/docs/api/props.md/#-code-submitfailed-boolean-code-

> submitFailed : boolean
Starts as false. If onSubmit is called, and fails to submit for any reason, submitFailed will be set to true. A subsequent successful submit will set it back to false.

> submitSucceeded : boolean
Starts as false. If onSubmit is called, and succeed to submit , submitSucceeded will be set to true. A subsequent unsuccessful submit will set it back to false.

> submitting : boolean #
