### ISSUE TITLE
react-native if onChange callback is async ConnectedField won't trigger the change action

### ISSUE THREAD

**Issue by TomaszChmielPagepro** [redux-form/redux-form#4391]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?
If onChange prop is async function ConnectedField does not trigger the change action. I belive this is because async function always returns a Promise instance so this condition is always true
https://github.com/erikras/redux-form/blob/84359b3fb5be9f62e030657100ea1ddede4c5ef7/src/ConnectedField.js#L132

### What is the expected behavior?
Maybe we should check for Promises here and wait resolve them and then use their result as value for defaultPrevented variable?

### Sandbox Link
https://codesandbox.io/s/l7vp6w6nyz

File: App.js
Line: 16

### What's your environment?
react-native, both iOS and Android

**Comment by TomaszChmielPagepro** [comment]
Looks like test need some fixes now. I will fix them as sson as possible. Just tell me if you think this is a good solution. Thanks!

**Comment by iamandrewluca** [comment]
This it seems more as a feature request.
As I see in code and docs, `onChange` does not support async functions.
Returning a truthy value from `onChange` in `ReactNative` works like `event.preventDefault()`
