### ISSUE TITLE
`onChange` prop with a returned value breaks custom fields

### ISSUE THREAD

**Issue by JonathanTR** [redux-form/redux-form#4401]
### Bug Report
If you define a custom `Field` component that calls `onChange` with the value of the field, providing an `onChange` prop to the field will prevent the `@@redux-form/CHANGE` event from firing, IF that `onChange` function returns an explicit value. 

I believe this may be related to https://github.com/erikras/redux-form/issues/3446

### What is the current behavior?
I've provided a [minimal Sandbox](https://codesandbox.io/s/n9kk00qw9j) to reproduce. Say I've created a custom field component called `Number` that is supposed to take the value of the input when it changes and update some other field.
```
const Number = ({ input }) => (
  <input
    type="number"
    {...input}
    onChange={({ target }) => input.onChange(target.value)}
  />
);

...

<Field
  name="number"
  component={Number}
  onChange={(val) => change("my-form", "some_other_field", val + 1)}
/>
```

This will prevent `@@redux-form/CHANGE` from firing because it returns a value, rendering the field effectively dead. However, if the `onChange` prop in `Field` returns undefined, the whole thing works just fine:
```
<Field
  name="number"
  component={Number}
  onChange={(val) => {
    change("my-form", "some_other_field", val + 1);
    return undefined;
  }}
/>
```

### What is the expected behavior?
I would expect a function provided as an `onChange` prop to `Field` to take the value provided and perform whatever operation with it, regardless of the return value of that function. There's a workaround to this, but it's very weird implicit behavior that I now need to document for future developers who might want to use these components.

In my case, I would like to be able to provide custom field components that fire `onChange` with their current value and then be able to perform further operations with that particular value. 

### Sandbox Link
https://codesandbox.io/s/n9kk00qw9j

### What's your environment?
```
"dependencies": {
    "react": "16.4.0",
    "react-dom": "16.4.0",
    "react-redux": "6.0.1",
    "redux": "3.5.2",
    "redux-form": "8.1.0"
  }
```

### Other information
I believe I've provided the most minimal case for this bug. Please let me know if there is any other information I can provide.

**Comment by Flibo** [comment]
For now, as a workaround, I've changed my `Field` level `onChange` prop names to `customOnChange`. Then in the inner component I use `onChange` like this:
```
onChange={value => {
  this.props.input.onChange(value);
  if (this.props.customOnChange) this.props.customOnChange(value);
}}
```
