### ISSUE TITLE
Upgrading to react-redux v7 moves caret to end of line after input change

### ISSUE THREAD

**Issue by gugu** [redux-form/redux-form#4437]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Editing the field in the middle moves caret at the end

### What is the expected behavior?
Editing the field in the middle edits the field in the middle

You can change react-redux version to v6 and the field is magically fixed: https://codesandbox.io/s/3kq0llj19q

### Sandbox Link
https://codesandbox.io/s/3kq0llj19q

### What's your environment?
![image](https://user-images.githubusercontent.com/75169/56083419-5f7bd100-5e2d-11e9-924f-e808a954d178.png)

### Other information
#4430 is related

Here is an example of redux vs redux-form editing: https://codesandbox.io/s/808nz9r2l

**Comment by gustavohenke** [comment]
There's plenty of issues on #4431, if you could contribute there/check if none of those are the same as yours, that would be lovely.
