### ISSUE TITLE
When try to set a input value with nested array, it goes as an empty array

### ISSUE THREAD

**Issue by paulocesarpcfj** [redux-form/redux-form#4477]
### Are you submitting a **bug report** or a **feature request**?

BUG

### What is the current behavior?

When dispatch this.props.change passing a payload with an object and inside it an array, it doesn't work. The array always is sent as empty, even with dynamic or fixed values.

```
                this.props.change(
                    'inputName',
                    { type: 'I need to set a type here', anyArray: [1, 2] },
                )
```

Result on redux-form state `{ type: 'I need to set a type here', anyArray: [] }`

### What is the expected behavior?
It is expected to have the array listed correctly.

### What's your environment?

ReduxForm 7.0.2, Google Chrome LTS, Node 8

**Comment by renatoagds** [comment]
@paulocesarpcfj This happens in the latest version of `redux-form`? Could you test that?
