### ISSUE TITLE
Immutable JS in bundle

### ISSUE THREAD

**Issue by topaxi** [redux-form/redux-form#4519]
### What is the current behavior?

The latest version of redux-form pulls in Immutable into the bundle.

### What is the expected behavior?

redux-form should only require/import Immutable if it is a hard-dependency.

### What's your environment?

create-react app & redux-form 8.2.5

### Other information
Steps to reproduce:

```bash
npx create-react-app myapp
cd myapp
yarn add redux react-redux redux-form
# import { reduxForm } from 'redux-form'; // and use somewhere in app
yarn build
npx source-map-explorer 'build/static/js/*.js'
```

**Comment by jamesmillerburgess** [comment]
I also noticed this while examining our bundle. Would be great if this could be removed.

**Comment by iamandrewluca** [comment]
~~Are you sure that you are not importing anything from `redux-form/immutable`?~~
> The latest version of redux-form pulls in Immutable into the bundle.
`immutable` is only included in `devDependencies` and is not installed when you install the library.
If you use something from `redux-form/immutable` and don't have `immutable` installed, it should throw some error that module is not found. Otherwise It could not be included into module by `redux-form`

**Comment by iamandrewluca** [comment]
The problem exists.

**Comment by renatoagds** [comment]
@iamandrewluca are you working on this? we should abstract the part that include immutable

**Comment by iamandrewluca** [comment]
As I tracked down, this issue #4313 will arise if we revert `immutable` code from `handleSubmit`. I'll try to fix it.

**Comment by ioanlucut** [comment]
+1

**Comment by DavidOrchard** [comment]
Could this be prioritized higher than it is now?  We can't afford to upgrade to redux v4 including redux-forms with this big a bundle increase.

**Comment by renatoagds** [comment]
@DavidOrchard feel free to open a PR and help us

**Comment by DavidOrchard** [comment]
Is doing the work the only way that I can get a release to have a specific bug fix and only that?
