### ISSUE TITLE
Async validation failed

### ISSUE THREAD

**Issue by vavdav** [redux-form/redux-form#4523]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
1) First I type name 'john' (which should fail validation)
2) Click outside (to trigger validation)
3) During validation click back into the input and write anything else (something valid)
4) It will still display validation message 'That username is taken' which is not correct because it is valid and you are not able to submit the form

### What is the expected behavior?
1) First I type name 'john' (which should fail validation)
2) Click outside (to trigger validation)
3) During validation click back into the input and write anything else (something valid)
4) It will not display a message 'That username is taken'

### Sandbox Link
I am using official documentation: 
https://redux-form.com/6.7.0/examples/asyncvalidation/

there is a link to sandbox:
https://codesandbox.io/s/nKlYo387

**Comment by iamandrewluca** [comment]
Async validation is triggered on blur. You should blur field to trigger async validation again
