### ISSUE TITLE
Typescript - warnings about immutable when building in version 8.2.4

### ISSUE THREAD

**Issue by captain-igloo** [redux-form/redux-form#4534]
### What is the current behavior?
Since 8.2.4 I am getting a bunch of warnings when I build my typescript project.  To reproduce:
```
git clone https://github.com/captain-igloo/redux-form-bug.git
cd redux-form-bug
npm install
npm run build

```
You will see warnings like "export 'Iterable' was not found in 'immutable'".   If you change redux-form to 8.2.3 the warnings disappear.

### What is the expected behavior?
No warnings.

### Sandbox Link
https://github.com/captain-igloo/redux-form-bug.git

### What's your environment?
redux-form 8.2.4 and above

### Other information
See https://github.com/erikras/redux-form/pull/4476

**Comment by esetnik** [comment]
I was able to fix the issue by adding `include` for `ts-loader`.

```js
const path = require("path");

module.exports = {
  mode: "development",
  entry: ["./src/index.ts"],
  resolve: {
    extensions: [".js", ".ts"]
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        include: path.join(__dirname, "src"),
        loader: "ts-loader"
      }
    ]
  }
};
```

**Comment by esetnik** [comment]
It's also working with the following ["vanilla" `ts-loader` configuration](https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla).

```js
// webpack.config.js
const path = require("path");

module.exports = {
  mode: "development",
  devtool: "source-map",
  entry: "./src/index.ts",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist")
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader"
      }
    ]
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js"]
  }
};
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "sourceMap": true
  }
}
```

**Comment by iamandrewluca** [comment]
@captain-igloo do you use `immutable` in your project?

**Comment by iamandrewluca** [comment]
It seems to be a problem with config. Try what @esetnik suggested.

`es/handleSubmit.js` imports `immutable` but `ts-loader` wants to import `es/immutable.js`

```
WARNING in ./node_modules/redux-form/es/structure/immutable/index.js 14:11-19
"export 'Iterable' was not found in 'immutable'
 @ ./node_modules/redux-form/es/immutable/Field.js
 @ ./node_modules/redux-form/es/immutable.js
 @ ./node_modules/redux-form/es/handleSubmit.js
 @ ./node_modules/redux-form/es/createReduxForm.js
 @ ./node_modules/redux-form/es/reduxForm.js
 @ ./node_modules/redux-form/es/index.js
 @ ./src/index.ts
 @ multi ./src/index.ts
```
