### ISSUE TITLE
When field is of type `file`, and `reduxForm` is configured to `destroyOnUmount: false`, it still destroys the uploaded file on Umount

### ISSUE THREAD

**Issue by gurbraj** [redux-form/redux-form#4541]
### Are you submitting a **bug report** or a **feature request**?
bug report.

my FileUpload component:

```
export const FileUpload = ({ input, helperText, ...rest }) => (
  <React.Fragment>
    <input
      type="file"
      onChange={event => {
        event.preventDefault();
        const files = [...event.target.files];
        input.onChange(files[0]);
      }}
      {...rest}
    />
    <p // MaterialUI::helperText compliant helper text
      style={{
        color: 'rgba(0, 0, 0, 0.54)',
        fontSize: '0.75rem',
        fontFamily: 'Roboto, Helvetica, Arial, sans-serif',
      }}
    >
      {helperText}
    </p>
  </React.Fragment>
);
```

form component that uses `FileUpload` (just showing ending):

```
export default reduxForm({ form: 'addPayee', destroyOnUnmount: false })(
  AddPayee
);
```

I can upload files fine, and all other fields keep their state when the `AddPayee`-component has been umounted

### What is the current behavior?
When field is of type `file`, and `reduxForm` is configured to `destroyOnUmount: false`, it still destroys the uploaded file on Umount

### What is the expected behavior?

When field is of type `file`, and `reduxForm` is configured to `destroyOnUmount: false`, it does NOT destroy the uploaded file on Umount

### What's your environment?
"redux-form": "^7.4.2",

**Comment by iamandrewluca** [comment]
@gurbraj what version of react do you use?
There is a known issue in `redux-form@7.4.2` that a input file is changing from uncontrolled to controlled component, but is still working with `react@15.6.2`, later version will throw an error.
Here is an example. Click unmount button, and see in console that file still exists in store.
https://codesandbox.io/s/redux-form-simple-example-8vp0m

Related issues
https://github.com/erikras/redux-form/issues/3686
https://github.com/erikras/redux-form/issues/1989

**Comment by gurbraj** [comment]
@iamandrewluca, i'm using `"react": "^16.8.6"`.

thanks for links -- will check out

**Comment by iamandrewluca** [comment]
@gurbraj did you found a solution?

**Comment by gurbraj** [comment]
@iamandrewluca unfortunately, i didn't have time to look further into this.

thanks though!

**Comment by iamandrewluca** [comment]
Ok, I'll close this for now, feel free to comment or open other issue. Thanks!
