### ISSUE TITLE
I haven't thought through this deeply so there are probably good reasons not to do this, but I would prefer to see something like this:

### ISSUE THREAD

**Issue by railsfactory-robin** [redux-form/redux-form#4547]
Attempted import error: 'submitForm' is not exported from 'redux-form'.

**Comment by iamandrewluca** [comment]
@railsfactory-robin Issue title should be something descriptive. Please read it again and try to understand yourself what is the request 🙂 

From description I think you want `redux-form` to export something like `submitForm`?

Whats your use case, that you would life this feature?
