### ISSUE TITLE
A Word Error at Demo Page

### ISSUE THREAD

**Issue by hazelGranger** [redux-form/redux-form#4551]
[https://redux-form.com/8.2.2/examples/material-ui/](https://redux-form.com/8.2.2/examples/material-ui/)
At this demo page, the label for the select should be "Color"  not "Age"
See screenshot here:
<img width="749" alt="Screen Shot 2019-10-17 at 11 22 32 AM" src="https://user-images.githubusercontent.com/10137066/66963713-d6da3800-f0d0-11e9-90f5-291d35ad5c93.png">

**Comment by goodwin64** [comment]
fix is here: https://github.com/redux-form/redux-form/pull/4558
