### ISSUE TITLE
Hi  My app is crashing whenever i enter  text  in forms .

### ISSUE THREAD

**Issue by maheshatti89** [redux-form/redux-form#4555]

**Comment by maheshatti89** [comment]
Hi  My app is crashing whenever i enter  text  in forms .I am  using redux form with custom  Text Input component.#Note: App is crashing only in Production build not in Debug mode .
App is crashing without any console errors.
tested logs in production build also using Logcat.
Kindly please please help me to resolve the issue

**Comment by iamandrewluca** [comment]
@maheshatti89 please first ask the question in the issue template, and we'll see.
We don't have any context what's happening in your app. Event better would be to provide a https://codesandbox.io example with your example crashing the app.
