### ISSUE TITLE
Code in "Initialize Form from State" examplein docs doesn't correspond 

### ISSUE THREAD

**Issue by pkail** [redux-form/redux-form#4559]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
See below.  

### What is the expected behavior?
See below.

### Sandbox Link
N/A

### What's your environment?

8.2.2.  This is not a problem with code.

### Other information
N/A

**Comment by pkail** [comment]
In the explanation it says:
1. Pass a enableReinitialize prop or reduxForm() config parameter set to true to allow the form the reinitialize with new "pristine" values every time the initialValues prop changes. To keep dirty form values when it reinitializes, you can set keepDirtyOnReinitialize to true. By default, reinitializing the form replaces all dirty values with "pristine" values.

2. Dispatch the INITIALIZE action (using the action creator provided by redux-form).
I can't find either the  enableReinitialize prop or the INITIALIZE action creator in the code.  I apologise if I have missed them.

**Comment by iamandrewluca** [comment]
https://github.com/redux-form/redux-form/blob/ccebdcd0270edd699b9c381a65fefe742fdadc90/src/createReduxForm.js#L308

https://redux-form.com/8.2.2/docs/api/reduxform.md/#-code-enablereinitialize-boolean-code-optional-

https://github.com/redux-form/redux-form/blob/ccebdcd0270edd699b9c381a65fefe742fdadc90/src/actions.js#L289

https://redux-form.com/8.2.2/docs/api/actioncreators.md/#-code-initialize-form-string-data-object-keepdirty-boolean-options-keepdirty-boolean-keepsubmitsucceeded-boolean-updateunregisteredfields-boolean-keepvalues-boolean-code-
