### ISSUE TITLE
form onSubmit receiving SyntheticEvent instead of values

### ISSUE THREAD

**Issue by invious** [redux-form/redux-form#4564]
This was working and I don't know why it suddenly is not.

I have one Field in my form, title. When I submit the form, i console log `values`. it does a page redirect to `/?title=` and shows me a `SyntheticEvent`

![image](https://user-images.githubusercontent.com/1996089/69038773-82202a80-09b8-11ea-8801-b093474fc758.png)

I tried to make a sandbox but it won't run 😢 
https://codesandbox.io/s/react-codesandbox-zon7u?fontsize=14&hidenavigation=1&theme=dark

**Comment by iamandrewluca** [comment]
@invious could you show some code, if can't recreate it in codesandbox?

**Comment by deadline98** [comment]
I feel like you're using the form wrongly. Looking at your codesandbox, you try to pass your custom `saveForm` function directly to the `onSubmit` of the form component: 

`<form onSubmit={saveForm}>` (wrong)

In order for redux-form to work, you have to pass `handleSubmit` - which you get from the props -
to `onSubmit`. So your code should look like:

`<form onSubmit={props.handleSubmit}>` (possibly destructure `handleSubmit` from props before using it)

And then pass your custom `saveForm` function to the `reduxForm()` initializer like so:

```
const Form = reduxForm({
  form: 'articleForm',
  validate,
  onSubmit: saveForm
})(ArticleForm)
```

**Comment by iamandrewluca** [comment]
Or if you have your function in same class or function

When class
```jsx
<form onSubmit={props.handleSubmit(this.saveForm)}>
```

When function in function
```jsx
<form onSubmit={props.handleSubmit(saveForm)}>
```

When from props
```jsx
<form onSubmit={props.handleSubmit(props.saveForm)}>
```

When in props have `onSubmit`
```jsx
<form onSubmit={props.handleSubmit}>
```
