### ISSUE TITLE
Screen reader(narrator) is reading incorrect total number of options available in drop-downs

### ISSUE THREAD

**Issue by HarkeshS** [redux-form/redux-form#4565]
### Are you submitting a **bug report** or a **feature request**?
**bug report**
Screen reader(narrator) is reading incorrect total number of options available in drop-downs of redux form

### What is the current behavior?
Screen reader(narrator) is reading incorrect total number of options available in drop-downs
like if drop down contains 2 options then screen reader is reading 3 options(one plus count).

### What is the expected behavior?
Screen reader(narrator) should read correct number of options as drop down has, not consider blank option in count.

### Sandbox Link
https://redux-form.com/6.5.0/examples/simple/ 

### What's your environment?
"redux": "4.0.0",
 "redux-form": "8.2.6",
"windows": 10

**Comment by iamandrewluca** [comment]
@HarkeshS I think this is not a `redux-form` issue, this is how the reader interprets the DOM.

**Comment by HarkeshS** [comment]
@iamandrewluca -Same I was able to repro at below link, which is simple redux form for demo, then how can you say this is not redux form issue.
https://redux-form.com/6.5.0/examples/simple/
