### ISSUE TITLE
./node_modules/redux-form-website-template/es/components/App.js Module not found: Can't resolve './App.scss' in '/Users/userA/Sites/promocode/node_modules/redux-form-website-template/es/components'

### ISSUE THREAD

**Issue by chiholiu** [redux-form/redux-form#4584]
### Are you submitting a **bug report** or a **feature request**?

In the first glance it seems a file is missing, so I would say feature request?

### What is the current behavior?

Getting an error that App.scss is missing or need to be resolved

### What is the expected behavior?

Auto added when doing npm install

### What's your environment?

NPM version 6.13.1
Node version v12.13.1

**Comment by iamandrewluca** [comment]
@chiholiu please answer the questions in the issue template.

**Comment by PriyaaaDharshini** [comment]
same issue i am also facing
