### ISSUE TITLE
Add support for selecting field to use in initial value (e.g. for DropdownList)

### ISSUE THREAD

**Issue by rikard-swahn** [redux-form/redux-form#4585]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
Given a Field rendering a react widgets DropdownList, like:
```jsx
<Field name='something' data={options} valueField="id" textfield="name"  component={renderDropdownList}...> 
```

Where the dropdown is initialized with a value, where the value is an object like this: 
```js
{
  id: 1,
  name: 'Test'
}
``` 
...there is no way (I think) to point to the 'id' property for matching against the id field in the "options" data.

### What is the expected behavior?
If possible, add a "initialValueField", which would be "id" in this case.

**Comment by iamandrewluca** [comment]
@rikard-swahn I can't see entire picture, what you are trying to do. Can you add more context to this?
I'm sure there is a way to solve this without adding a feature.

**Comment by rikard-swahn** [comment]
@iamandrewluca Yes, I'm trying to set the selected value of a dropdown based on existing state, where the selected value is an object in my state. 

I solve this today by mapping the object to the value of "id". So I have a lot of code in reducers which looks like this:

```
  data = data.updateIn(['objectProperty'], obj => {
    return obj.get('id')
  });
```
It would be nice to be able to remove all this, and just define what property of the object to use in the dropdown.

**Comment by iamandrewluca** [comment]
Can you provide a simple example using https://codesandbox.io/ ?

**Comment by rikard-swahn** [comment]
I realized that this is probably because my state data (which is used for the initial state) is in ImmutableJS-format. I'm guessing redux-form is not able to get properties from the data.
