### ISSUE TITLE
Select Dropdown color impacted by Operating system.

### ISSUE THREAD

**Issue by HarishRMaryada** [redux-form/redux-form#4588]
### select dropdown on hover should show the according to style sheet applied

Images shows the Orange color on Ubuntu and Blue on IOS and Windows
<img width="1105" alt="img2" src="https://user-images.githubusercontent.com/42580288/71511637-11bed000-28b9-11ea-93f8-b3536522b65d.png">
<img width="1188" alt="img1" src="https://user-images.githubusercontent.com/42580288/71511638-12576680-28b9-11ea-9801-c7b41d51eec7.png">

**Comment by iamandrewluca** [comment]
@HarishRMaryada this is not related to `redux-form`, this is the behaviour of the os/browser. Look Chromium on Ubuntu.
![image](https://user-images.githubusercontent.com/1881266/71586903-6b770280-2b24-11ea-9c49-11fed2708472.png)

**Comment by HarishRMaryada** [comment]
Thanks,@andrewluca. The color issue is with the select tag itself,it behave differently in different OS.
