### ISSUE TITLE
incorrect documentation for field type select-multiple

### ISSUE THREAD

**Issue by 7sean68** [redux-form/redux-form#4592]
### Subject of the issue
incorrect documentation for `Field` `type` prop value [select-multiple](https://github.com/redux-form/redux-form/blob/e7ce5aec2bf0e24574e6f5f90bc04b9815c8e52e/src/createFieldProps.js#L62) as [select-multi](https://github.com/redux-form/redux-form/blob/39588404bb0f332d05257443c705e623ab3f8cc6/docs/api/Field.md#L135).

**Comment by iamandrewluca** [comment]
@7sean68 thanks!
