### ISSUE TITLE
Normalizing field values causes the caret to jump to the end of the input

### ISSUE THREAD

**Issue by ChrisCraig68** [redux-form/redux-form#4603]
### Normalizing field values causes the caret to jump to the end of the input

When Normalizing the value of a field it causes the caret/ cursor to jump to the end of the input. This is frustrating if you want to amend a characters after entering an initial value because as soon as the user starts to type the caret immediately jumps to the end of the input.

### Your environment

Using 8.2.2

### Steps to reproduce

You can see this bug in the Normalizartion example in the redux-form docs.
https://redux-form.com/8.2.2/examples/normalizing/

1. Type a value into either the phone or "shout" field
2. Try and amend the first two characters you entered into that field
3. After typing the first character, the caret/ cursor jumps to the end of the input

### Expected behaviour

The caret will not jump to the end of the input

### Actual behaviour

The caret jumps to end of the input after changing or adding a new value to the input.

**Comment by ChrisCraig68** [comment]
It seems this issues has been reported a few times in the past but has been continuously closed with no feedback. Lastest example can be found here: https://github.com/redux-form/redux-form/issues/4480

**Comment by iamandrewluca** [comment]
Hmm, strange behaviour. If you look in the example first two fields are almost the same, but jumping only happens on second field. On first field cannot reproduce.

**Comment by ChrisCraig68** [comment]
It does happen on the first field (username) but only if you try and type and uppercase character into that field.

**Comment by kopax** [comment]
> It seems this issues has been reported a few times in the past but has been continuously closed with no feedback. Lastest example can be found here: #4480

I got closed but not because of the feedback

**Comment by iamandrewluca** [comment]
> One advice..do not use that lib use it is trash.

That's rude. Better to say.

> One advice..do not use this lib, it has a lot of issues.

**Comment by kopax** [comment]
Well, a bit, sorry to say but that's not my word. Many people have lost a lot of time because of that lib, the author of redux-form itself recommend to use the redux-final-form (which he also wrote) because of all the issues. You should definitely not use it, and the author judged this library should be thrown to trash in profit of final-form.

**Comment by iamandrewluca** [comment]
We are using this library almost two years in production, and don't bother about small issues :slightly_smiling_face: 

The main generator of the issues, is because this library tried to make every user happy, and added a lot of fatures.

**Comment by kopax** [comment]
I strongly advise you to migrate your form to use final-form, this will drastically improve your application performance.

**Comment by iamandrewluca** [comment]
> this will drastically improve your application performance.

I don't understand what kind of forms people have, that they struggle about performance. :smile:

redux-form immutablejs :eyes:

> I strongly advise you to migrate
I have a dream to rewrite redux-form@v9 with hooks and drop immutablejs support

**Comment by iamandrewluca** [comment]
After some investigation, this behaviour will happen also without `redux-form`. Is the way React and DOM works. `redux-form` can't fix this issue because we don't know what exactly happened with the value.

Here is a sandbox with the issue
https://codesandbox.io/s/react-cursor-jump-wmqp1

Here is a sandbox with an attemp to restore cursor
https://codesandbox.io/s/react-cursor-jump-fixed-zh5lp

**Comment by iamandrewluca** [comment]
https://github.com/facebook/react/issues/955

**Comment by iamandrewluca** [comment]
Solution would be to use a react input mask library that takes care of cursor restoring
