### ISSUE TITLE
AutoComplete not clear when Reset fired 

### ISSUE THREAD

**Issue by minaairsupport** [redux-form/redux-form#4607]
### Subject of the issue
AutoComplete not cleared when reset method fired 

Describe your issue here.
when I press clear values button which result of calling Reset method inside Redux form its not clearing the UI of autoComplete 

### Your environment
all environment 

### Steps to reproduce
I attach this sandbox link 
https://codesandbox.io/s/redux-form-material-ui-example-m7lhy

I have a list of components there first one is rendered by autocomplete component 
choose any item then click clear values button 

result AutoComplete Ui still has the value selected 

### Expected behaviour
the value inside autocomplete should be removed 

### Actual behaviour
value selected still there

**Comment by iamandrewluca** [comment]
Please fix example in sandbox because is broken.

**Comment by minaairsupport** [comment]
sorry I fixed it, AutoComplete is the first component

**Comment by iamandrewluca** [comment]
@minaairsupport I think something wrong is with the component you use.
Add a `console.log(input.value)` in `renderAutocomplete` and you will see that `redux-form` is passing value correctly

**Comment by minaairsupport** [comment]
I just tried that now and it's not you could check yourself

**Comment by iamandrewluca** [comment]
Your not passing correct `value` to `Autocomplete` 
use `value={input.value}`

**Comment by minaairsupport** [comment]
yea I just tried that too but still not fix the issue, I think the issue come from freeSolo option in AutoComplete

**Comment by iamandrewluca** [comment]
I replaced `value={value}` with `value={input.value}` and it worked.
