### ISSUE TITLE
Form validation not working and TypeError on submit form

### ISSUE THREAD

**Issue by Sineliad** [redux-form/redux-form#4610]
### Form validation not working and TypeError on submit form
The form is submitting without validation and throw and TypeError

### Your environment

- **OS**: 
LSB Version:   core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: neon
Description:    KDE neon User Edition 5.18
Release:        18.04
Codename:       bionic
- **Packages**:  
"react": "^16.9.0",
"redux": "4.0.4",
"react-redux": "7.1.1",
"redux-form": "^8.3.0",

- **Env**: 
node: v8.10.0
npm: 6.5.0
yarn: 1.12.3
browser: Versión 75.0.3770.100 (Build oficial) (64 bits)

### Steps to reproduce

Github: https://github.com/Sineliad/react-boilerplate-redux-form
Demo Page: https://boilerplatereduxform.netlify.com/

In the demo page fill the form "React Redux Form" and click in "Submit" and see the error in the console.

In the repository the form is in the folder: app/containers/HomePage/

The form: https://github.com/Sineliad/react-boilerplate-redux-form/blob/master/app/containers/HomePage/SyncValidationForm.js

Where I call the from: https://github.com/Sineliad/react-boilerplate-redux-form/blob/master/app/containers/HomePage/index.js

### Expected behaviour
Validate the form first and get the data on submit 

What should happen?
Validate the form first and then submit the form if all data are valid

### Actual behaviour
What happens instead?
Submit the form without validate the data and display TypeError: 

15.bffa0ad389f32cbd40ec.chunk.js:1 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLInputElement'
    |     property '__reactInternalInstance$hsf4nyq060s' -> object with constructor 'Wr'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at 15.bffa0ad389f32cbd40ec.chunk.js:1
    at d (npm.babel.364fb6b163e5042f4cf5.chunk.js:1)
    at Generator._invoke (npm.babel.364fb6b163e5042f4cf5.chunk.js:1)
    at Generator.e.<computed> [as next] (npm.babel.364fb6b163e5042f4cf5.chunk.js:1)
    at ee (15.bffa0ad389f32cbd40ec.chunk.js:1)
    at u (15.bffa0ad389f32cbd40ec.chunk.js:1)
    at 15.bffa0ad389f32cbd40ec.chunk.js:1
    at new Promise (<anonymous>)
    at p (15.bffa0ad389f32cbd40ec.chunk.js:1)

Thanks

**Comment by Sineliad** [comment]
![ReduxForm2](https://user-images.githubusercontent.com/9753852/74580051-ba0e1e00-4f65-11ea-94b9-2d8a95493873.png)
![ReduxForm1](https://user-images.githubusercontent.com/9753852/74580054-bc707800-4f65-11ea-91ba-407c31dc36ba.png)

**Comment by iamandrewluca** [comment]
Try to change
https://github.com/Sineliad/react-boilerplate-redux-form/blob/0a4f881a697e7e95114bf97e42deabd0bba5b434/app/containers/HomePage/index.js#L92

Into
```jsx
          <SyncValidationForm onSubmit={handleFormSubmit} />
```

And please read the docs for `handleSubmit`
https://redux-form.com/8.3.0/docs/api/props.md/#-code-handlesubmit-eventorsubmit-function-code-

**Comment by Sineliad** [comment]
Thanks a lot, it`s works. I am going to read with more detail handleSubmit. Thanks :)
