### ISSUE TITLE
How to prevent Field update Redux Store in Edit View?

### ISSUE THREAD

**Issue by andrewguo24** [redux-form/redux-form#4612]
Hi all, I have a form with four fields, first name, last name, mobile and email. In edit view, before client save changes, how can I prevent Field updating Redux Store before clicking on Save Changes?

**Comment by iamandrewluca** [comment]
@andrewguo24 redux-form it keeps all the values into redux, you can prevent each field from changing, redux state, but you will have emtpy fields. What is your requirement? maybe there is another solution.

**Comment by andrewguo24** [comment]
@iamandrewluca I have an edit view for these Fields. In this edit view, I have a Save Changes Button. Before client click on Save Changes Button, I don't want any changes being dispatched to redux store. Do you have any solution?

**Comment by iamandrewluca** [comment]
> Before client click on Save Changes Button

`redux-form` can't work without redux. When you type any letter into an input, the changes are dispatched to redux, event before client clicks save button.

> I don't want any changes being dispatched to redux store.

Why you don't want any changed being dispatched?

Maybe `redux-form` is not the library you want, if so, take look at https://final-form.org/react

**Comment by andrewguo24** [comment]
@iamandrewluca Thanks for your reply. I have an edit view with cancel and save changes. If the client make some changes, and then cancel. The changes still show which I don't want see these changes. That's why I don't want see these changes being dispatched to redux store before clicking on save changes button.

**Comment by iamandrewluca** [comment]
@andrewguo24 maybe you want to use `props.reset()` to reset form to initial state?

**Comment by iamandrewluca** [comment]
If you still have the question please ask on our community forums.

https://gitter.im/erikras/redux-form
https://stackoverflow.com/questions/tagged/redux-form
https://spectrum.chat/redux-form
