### ISSUE TITLE
React v16.13.0 - Field validation is triggering a "Warning: Cannot update a component from inside..."

### ISSUE THREAD

**Issue by igodorogea** [redux-form/redux-form#4619]
### Subject of the issue

After React update to v16.13.0 `Field` validation is triggering 
```
Warning: Cannot update a component from inside the function body of a different component.
```
on initialize and on input.

### Steps to reproduce

1. Go to https://codesandbox.io/s/redux-form-simple-example-nn8nv
2. Start typing in the input.
3. Warning appears in console.

### Other information

**React v16.13.0 changes**
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render

**Comment by pulgaroja** [comment]
I can confirm this is happening for me as well, here's a list of my versions:

```"react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.5",
    "redux-form": "^8.3.0",```

**Comment by b-alidra** [comment]
+1

**Comment by mateuswolkmer** [comment]
Can somebody confirm if this is being worked on, and if it is still safe to use validation even with the warning (commercial application)?

**Comment by iamandrewluca** [comment]
> if it is still safe to use validation even with the warning (commercial application)?

It is safe.

> Can somebody confirm if this is being worked on

I'll take some time next week to investigate the problem.

If the warning bothers you, you can save react as a exact verion right now.

**Comment by esetnik** [comment]
I tried to implement a failing test case for this bug but I wasn't able to get the console errors to generate in the test environment. The below test case should fail (but currently passes) as it's as close as possible to the [codesandbox str](https://codesandbox.io/s/redux-form-simple-example-nn8nv). My guess is that `TestUtils.Simulate.change()` doesn't execute the buggy code or possibly that it only occurs during a race condition which isn't reproducible in the test environment. Anyone have any ideas how to make this test fail?

```js
    it('should not have any console errors when using field level validation', () => {
      const store = makeStore()
      const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation()
      const firstNameInput = jest.fn(props => <input {...props.input} />)

      const required = jest.fn(value => {
        return value => (value ? undefined : 'required')
      })

      const SimpleForm = props => {
        const { handleSubmit, pristine, submitting } = props
        return (
          <Form onSubmit={handleSubmit}>
            <div>
              <label>First Name</label>
              <div>
                <Field
                  name="firstName"
                  component={firstNameInput}
                  type="text"
                  placeholder="First Name"
                  validate={required}
                />
              </div>
            </div>
            <div>
              <button type="submit" disabled={pristine || submitting}>
                Submit
              </button>
            </div>
          </Form>
        )
      }

      const TestForm = reduxForm({
        form: 'simple' // a unique identifier for this form
      })(SimpleForm)
      const dom = TestUtils.renderIntoDocument(
        <Provider store={store}>
          <TestForm />
        </Provider>
      )

      const input = TestUtils.findRenderedDOMComponentWithTag(dom, 'input')

      expect(consoleErrorSpy).not.toHaveBeenCalled()

      input.val = 'test'
      TestUtils.Simulate.change(input)
      expect(required).toHaveBeenCalledTimes(1)

      consoleErrorSpy.mockRestore()
    })
```

**Comment by skywalkery** [comment]
@esetnik Hi, for me it is reproducible with two requirements: the presence of initialValues and validate function. May be it will be useful:
```js
import React from 'react';
import { createStore, combineReducers } from 'redux';
import { Provider } from 'react-redux';
import { reducer as reduxFormReducer, reduxForm, Form, Field } from 'redux-form';
import { mount } from 'enzyme';

it('should not have any console errors', () => {
  const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();
  const reducer = combineReducers({
    form: reduxFormReducer,
  });
  const store = createStore(reducer);

  const required = value => (value ? undefined : 'required');

  const SimpleForm = () => (
    <Form onSubmit={() => {}}>
      <Field name="firstName" component="input" validate={required} />
    </Form>
  );

  const TestForm = reduxForm({
    form: 'simple',
    initialValues: {
      firstName: 'value',
    },
  })(SimpleForm);
  const dom = mount(
    <Provider store={store}>
      <TestForm />
    </Provider>
  );

  const form = dom.find(SimpleForm);
  expect(form.length).toEqual(1);

  expect(consoleErrorSpy).not.toHaveBeenCalled();
  consoleErrorSpy.mockRestore();
});
```

**Comment by esetnik** [comment]
@skywalkery that's an interesting observation although the original str https://codesandbox.io/s/redux-form-simple-example-nn8nv reported by @igodorogea notably does not use `initialValues`. Maybe these are two separate bugs with the same symptoms?

**Comment by igodorogea** [comment]
@esetnik 
> reported by @igodorogea notably does not use `initialValues`

Yes, the live example does not, but the it is mentioned in issue description.

> Maybe these are two separate bugs with the same symptoms?

No, the issue is caused by validation, and whenever it's called, be that on initialization or during user input.

**Comment by esetnik** [comment]
@igodorogea it looks like for some reason the bug is triggered with enzyme `mount` and not `TestUtils.renderIntoDocument`.

The following test case using `initialValues` still passes for me:

```js
    it('should not have any console errors when using field level validation with initialValues', () => {
     const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation();
      const store = makeStore()
      const firstNameInput = jest.fn(props => <input {...props.input} />)

      const required = jest.fn(value => {
        return value => (value ? undefined : 'required')
      })

      const SimpleForm = props => {
        const { handleSubmit, pristine, submitting } = props
        return (
          <Form onSubmit={handleSubmit}>
            <div>
              <label>First Name</label>
              <div>
                <Field
                  name="firstName"
                  component={firstNameInput}
                  type="text"
                  placeholder="First Name"
                  validate={required}
                />
              </div>
            </div>
            <div>
              <button type="submit" disabled={pristine || submitting}>
                Submit
              </button>
            </div>
          </Form>
        )
      }

      const TestForm = reduxForm({
        form: 'simple',
        initialValues: {
          firstName: 'value'
        }
      })(SimpleForm)
      const dom = TestUtils.renderIntoDocument(
        <Provider store={store}>
          <TestForm />
        </Provider>
      )

      const input = TestUtils.findRenderedDOMComponentWithTag(dom, 'input')

      expect(consoleErrorSpy).not.toHaveBeenCalled()
      consoleErrorSpy.mockRestore()
    })
```

**Comment by BranigansLaw** [comment]
I'm having the same issue with `initialValue` and `validation`. Good to hear @iamandrewluca is looking into this

**Comment by sfdev-div** [comment]
From my observations, this issue could be avoided by using `asyncValidate` (instead of synchronous `validate`). Most probably, it wont work in all cases, but might be tried as temporal solution though. If I understand it right, async validator simply runs outside of current rendering cycle, what prevents state update of `Field` wrapped component in same 'thread'.

**Comment by BranigansLaw** [comment]
@sfdev-div I gave `asyncValidate` a try and the validation errors just pop up again after you try and submit instead of on the first load.

**Comment by finom** [comment]
Any news on that?

**Comment by iamandrewluca** [comment]
React team released https://github.com/facebook/react/releases/tag/v16.13.1 that reverts this warning

> Revert warning for cross-component updates that happen inside class render lifecycles (componentWillReceiveProps, shouldComponentUpdate, and so on). (@gaearon in #18330)

Can someone confirm that warning is not showed when using `react@16.13.1` ?

**Comment by gaearon** [comment]
Note it doesn't "revert this warning", it only reduces the cases in which it fires.

**Comment by gaearon** [comment]
I guess the release note is a bit confusing, it reverts the unintended cases, but keeps the intended ones.

**Comment by iamandrewluca** [comment]
Thanks for the note!

**Comment by igodorogea** [comment]
I can confirm that when using `react@16.13.1` the warning is not showed anymore.

Here is the proof:
https://codesandbox.io/s/redux-form-simple-example-f447i

**Comment by iamandrewluca** [comment]
@igodorogea Thanks! 🙂

**Comment by finom** [comment]
I also confirm that 🎉

**Comment by Smasherr** [comment]
I confirm not having this warning anymore with `react@16.13.1`

**Comment by Ranfer** [comment]
I still have "warning" in react@16.13.1, validate function on a custom child component.

**Comment by ybakhshi** [comment]
Thanks. i confirm too! i was going crazy with the warnings! but updating to @16.13.1 solved my issues

**Comment by henryle251** [comment]
I also confirm that 🎉

**Comment by gaearon** [comment]
I think we have enough confirmations. :-) There's no need to post more.

**Comment by alex9110** [comment]
Problem still exists. Updating to 16.13.1 did not help.

**Comment by mateus21** [comment]
@alex9110, don't forget to update react-dom to 16.13.1

**Comment by BranigansLaw** [comment]
I upgraded to 16.3.1 as well and it fixed this issue

**Comment by Shariaty** [comment]
I updated the react to 16.13.1 and I confirm that it solve the problem for me too. TNX @igodorogea

**Comment by fagsoft1** [comment]
Updating to 16.13.1 both, React and the Dom, did not help. I'am getting the same problem.

**Comment by iamandrewluca** [comment]
@fagsoft1 what is returning this command?
```
npm info react version
```

**Comment by fagsoft1** [comment]
> @fagsoft1 what is returning this command?
> 
> ```
> npm list react
> ```

developmen@1.0.1 /Users/fabioandresgarciasanchez/PycharmProjects/react-nextjs-django/BaseProyectos
└── react@16.13.1

**Comment by iamandrewluca** [comment]
Cand you please create a sandbox with an example similar to yours, that shows the warning?

**Comment by fagsoft1** [comment]
> Cand you please create a sandbox with an example similar to yours, that shows the warning?

I will do it. I have found when in triggering the error. It happens when I use Synchronous Validations.
At the moment that I write something in the field, it says:

> react_devtools_backend.js:6 Warning: Cannot update a component from inside the function body of a different component.
>     in Form(Component) (created by ConnectFunction)
>     in ConnectFunction (created by Connect(Form(Component)))
>     in Connect(Form(Component)) (created by ReduxForm)
>     in ReduxForm (created by Context.Consumer)
>     in Hoc (created by ReduxForm)
>     in ReduxForm (created by Login)
>     in div (created by Login)
>     in Login (created by Context.Consumer)
>     in Route
>     in Switch
>     in Suspense
>     in Unknown (created by App)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (created by App)
>     in ThemeProvider (created by App)
>     in ProvideAuth (created by App)
>     in Provider (created by App)
>     in App (created by HotExportedApp)
>     in AppContainer (created by HotExportedApp)
>     in HotExportedApp 

But when I run without validate, it works properly but without validations.

**Comment by iamandrewluca** [comment]
Yes. This is exactly the case that is in issue description. In sandbox mentioned in issue description if you change react version to 16.13.1 Warning dissapears.

**Comment by fagsoft1** [comment]
> Yes. This is exactly the case that is in issue description. In sandbox mentioned in issue description if you change react version to 16.13.1 warning dissapears. Waiting a sandbox from you.

Ok, I made a sandbox to show you the problem, but it works properly. So, I tried to install everything step by step to find out with could've been the issue and after too much time I got it.

Everything was working ok but when I try to set up my project to be used with HOT reload at the moment that I put this in my webpack config:

>         alias: {
>              'react-dom': '@hot-loader/react-dom'
>          }

It begins triggering the message. Now, I'm looking for needing or not to use this to get Hot Reload works properly, is not, so I will take off that piece of code from my webpack config.

Do you have any advise for this issue?

Thanks.

**Comment by iamandrewluca** [comment]
Unfortunately I dont have any advice, maybe @gaearon can give some hints.

Related issues:
https://github.com/hot-loader/react-dom/issues/35
https://github.com/gaearon/react-hot-loader/issues/1438

**Comment by gaearon** [comment]
My advise is to `react-hot-loader` from your project. It's a huge hack and you're essentially running a different build of React than the one we ship. No guarantees around how that one works.

If you want hot reloading, look into [this plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) as alternative. We're planning to make it an official integration soon once a few more issues are worked out.

**Comment by xuniaoji** [comment]
Hey, @iamandrewluca thanks for following up, will you do anything to fix this? I still got the warning with react@16.13.1

**Comment by iamandrewluca** [comment]
@xuniaoji please be sure that you are using `react@16.13.1`. You can check with this command.

```
npm list react
```

If you are sure that have the latest react version and have the warning, please create a sandbox that would replicate your env.

**Comment by exzizt** [comment]
Same

**Comment by Relax594** [comment]
still seeing this on validate and normalize, even with react 16.13.1

**Comment by thany** [comment]
Still having this problem too.

**Comment by vijaychouhan-rails** [comment]
Still waiting for a solution

**Comment by TarasKhust** [comment]
Still waiting for a solution

**Comment by Asday** [comment]
Recently updated to Expo SDK 39, which brought React 16.13.1 with it, and I'm encountering this issue.  It doesn't appear to affect anything but it's highly annoying to have an error pop up where I want to tap every time any render happens.

**Comment by jwilson114** [comment]
Same as Asday

**Comment by anurbecirovic** [comment]
Still the issue, hope for the fix.

**Comment by sbidolach** [comment]
I can confirm that I have this same warning message with the below configuration:

```
"expo": "^39.0.0",
"react": "16.13.1",
"react-redux": "^7.2.2",
"react-router-redux": "^4.0.8",
"redux": "^4.0.5",
"redux-form": "^8.3.7",
"redux-persist": "^6.0.0",
"redux-thunk": "^2.3.0",
```

It seems that everything works but the message is irritating

**Comment by sdandois** [comment]
I have this warning in react-native, there is no react-dom package in yarn.lock

**Comment by Anuj-Raghuvanshi** [comment]
I am also using this with react-native and getting same error. Anyone have proper solution?

**Comment by VitamineC** [comment]
Same problem with react 16.13.1 and 0.63.3 RN + expo

**Comment by jordanrios94** [comment]
Is there plans for of a solution for react native apps built with expo?

**Comment by 026binit** [comment]
still looking for solutions

**Comment by jordanrios94** [comment]
I've migrated to [react final form](https://github.com/final-form/react-final-form).

If you not heard of this package, it was made by the same author of redux form.

The migration is very easy and in fact did not have change much of the form code. i.e. validation, fields, onSubmit, submitting, and so on.

I recommend very much to use as does the job exactly like in redux form without the extra configuration in redux.

**Comment by Brad19** [comment]
@sdandois , @anujraghuvanshi 
I started a project in react native 6 months ago. I started getting this warning. I thought i can look into that at the end.  Now i'm more worried on this. Does anyone has any solution for React native. If someone could advise me on this, it'll be a great deal for me.

Here is my package.json
  react: 16.13.1,
  redux-form: ^8.3.7,
  react-native: ^0.63.3
  react-redux : ^7.0.3
 react-native-navigation: ^7.16.0

Cheers,
Brad

**Comment by vijaychouhan-rails** [comment]
@Brad19 I was also using the same lib and getting started warning messages, I moved to [Formik Form](https://github.com/formium/formik) and got a good result, and working well nowadays.

**Comment by Brad19** [comment]
@vijaychouhan-rails .

Thanks for responding.

Are you suggesting that we don't have a fix in redux-form and the solution is to get off from redux-form here. Also btw I've heard about Formik form. The question is here is that i've to re-write few pages again to wire up for alternatives like Formik Form

Please advise.

Cheers,
Brad
