### ISSUE TITLE
Itering Fields {Select} with same label name

### ISSUE THREAD

**Issue by pcolina** [redux-form/redux-form#4631]
I am iterating an Array of Objects. I am rendering a form for each Object to update their values. All this inside a Table Component with a Expansion component in each row. So I have n-forms with a different key/name  for each and same names for each inside <Fields>. But When I change the name value it change me all Fields with name = 'myName'. If I try give them a unique name, like this: name={slot.name + "_name"} . Doing that It is solve but maybe  is there another smart way. Anyway If I want to give a Init state with

```js
const initData = {
  {slot.name + "_name"} : 'RED',
};
```

obviously it doesnt work, I apologize for my bad  English. Can anybody help me ?

**Comment by iamandrewluca** [comment]
@pcolina can you show how you call `reduxForm` HOC? Each form has to have it's own unique name.

```js
const MyForm = reduxForm({})(function (props) {
  /* ... */
})

const rows = [
  { id: 1, /* ... */ },
  { id: 2, /* ... */ },
]

function YourTable() {
  return rows.map(row => (
    // this `form` prop will be passed to `reduxForm`
    // and should be unique
    <MyForm form={`form-${row.id}`} />
  ))
}
```
