### ISSUE TITLE
setting Initial value in a select field

### ISSUE THREAD

**Issue by pcolina** [redux-form/redux-form#4633]
I am trying set a initialvalue into a select similar to  the example from https://codesandbox.io/s/MQnD536Km. But Instead with an onClick event in the componentDidMount method because they will  came from DB. At the moment I have difficulties with state so the first step is set a constant as Initial values . My App works recover from DB, save and remove but doesnt set the init values. I think is about the compose function maybe....

My js file is something like this

`
Import ....

export class EditSlot extends React.PureComponent {
  data = {
    type: 'Default Type',
  };

componentDidMount() {
     //   this.props.load(data);  //in the future
}

render() {
    const {
        dispatch, ..... , ..... , ....,  slot, type, load
      } = this.props;

    const types = ['Text', 'Boolean', 'Categorical']

  return (
     <form key="slotForm"
        onSubmit={handleSubmit(() => { dispatch(saveSlot({ slot })) })}
        >
        <Expansion
              name={slot.name}>

<React.Fragment>
            <FlexRow
                 key={slot.name}
                 style={{
                      flexWrap: 'wrap',
                      justifyContent: "space-between"
                   }}
            >
           ..... Others Fields here ......

            <Field
                name=type
                component="select"
                fullWidth
                label="Texto"
                type="text"
                style={{ flexBasis: "48%" }}
              >
                <option value="">Select  the type ...</option>
                {types.map(typesOption => (
                  <option value={typesOption} key={typesOption} >
                    {typesOption}
                  </option>
                ))}

         </React.Fragment>
       </Expansion>
    </form>
);
}

const mapStateToProps = (state) => {
  return {
    initialValues: {
      type: "My Default type",
    }
  }
 // In the future
     //state => ({
         //initialValues: state.reducer.data, // pull initial values from account reducer
      //  })
}

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
    load: loadAccount,
  };
}

const withForm = reduxForm({
  form: 'slotForm',
  enableReinitialize: true
  });

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,

);
const withReducer = injectReducer({ key: 'slotForm', reducer });
const withSaga = injectSaga({ key: 'slotForm', saga });

export default compose(
  withReducer,
  withSaga,
  withForm,
  withConnect
)(EditSlot);
`

**Comment by iamandrewluca** [comment]
@pcolina please ask questions on community forums. When you created the issue you had that option.
Also please indent the code because is unreadable.
