### ISSUE TITLE
Improve isSubmissionError & SubmissionError to be less error-prone with Terser

### ISSUE THREAD

**Issue by faiwer** [redux-form/redux-form#4641]
### Problem

Good day. I found an interesting bug. In my code. But when I looked at `redux-form` code I figured out that there's also something that can be better.

We have this (in our codebase):
```js
export const isReduxFormError = error => error.name === 'SubmissionError';
```
Like you had [previously](https://github.com/redux-form/redux-form/pull/4331/files). 

In prod mode webpack+Terser generated mangled code where error constructor name became just `"t"`. So our code got broken.

Then I opened source of `redux-form` and found there this:
```js
var isSubmissionError = function isSubmissionError(error) {
  return error && error.name === SubmissionError.name;
};
```

It's better than our buggy variant. But actually it's just a `error.name !== 't'` comparison (where `t` varies). It's brittle, because Terser can set the same function name (e.g. "t") to any other error constructor. It'll lead to strange problems when these errors are considered as validation errors.

### Expected behavior

It may be completely non-error-prone.

### Alternatives

This is current state of `SubmissionError` fabric:
```js
var SubmissionError =
/*#__PURE__*/
function (_ExtendableError) {
  _inheritsLoose(SubmissionError, _ExtendableError);

  function SubmissionError(errors) {
    var _this;

    _this = _ExtendableError.call(this, 'Submit Validation Failed') || this;
    _this.errors = errors;
    return _this;
  }

  return SubmissionError;
}(ExtendableError);
```
This code may set manually a proper name to its errors. Or it can set a new field to them. Or maybe something else that doesn't relay on constructor-name.

Thanks.

**Comment by iamandrewluca** [comment]
Fixed in https://github.com/redux-form/redux-form/releases/tag/v8.3.4
