### ISSUE TITLE
initialValues available after update

### ISSUE THREAD

**Issue by motoedie** [redux-form/redux-form#4642]
### Subject of the issue

Form is rendered twice and initialValues are rendered with update. Validation is started immediately without initialValues.

Form is rerendered when initialValues are saved to redux. It is unnecessary update. Calling validate() function without initialValues isn't correct neither. This didn't happen in version 7.4.2 because initialValues were available immediately.

### Your environment

- **OS**: macOS 10.15.3
- **Packages**: redux-form 8.3.0, react 16.12.0, redux 3.6.0, react-redux 7.2.0
- **Env**: Chrome 80

### Steps to reproduce

1. Go to https://codesandbox.io/s/redux-form-simple-example-94gdw
2. App crashed in validate() function because initialValues aren't available yet.
3. If you check `initialized` prop, application works https://codesandbox.io/s/redux-form-simple-example-31jpk

### Expected behaviour

initialValues should be available in first render and also in validate() function.

### Actual behaviour

initialValues are available after component update. validate() function is called without initialValues.

**Comment by erikras** [comment]
Published fix in [`v8.3.10`](https://github.com/redux-form/redux-form/releases/tag/v8.3.10).
