### ISSUE TITLE
Why redux form can't send value if we remove default <option /> from input type select?

### ISSUE THREAD

**Issue by mdsaon** [redux-form/redux-form#4649]
I have the following form component and when I have removed the <option />,I am not getting the value of "level" after submitting the form.

Here is the Sandbox Link: https://codesandbox.io/s/throbbing-smoke-84b1n?file=/src/AddNewForm.jsx

**Comment by iamandrewluca** [comment]
Please use codeblocks and please format your code blocks. If can do so here: https://prettier.io/playground/

**Comment by mdsaon** [comment]
For some reasons, even though,I have used prettier, after updating the section, it didn't format the actual code, But,I have created the sandbox here for your convenience.
https://codesandbox.io/s/throbbing-smoke-84b1n?file=/src/AddNewForm.jsx

**Comment by iamandrewluca** [comment]
@mdsaon sandbox is good. What do you mean with `redux form can't send value` ?

**Comment by mdsaon** [comment]
The thing is that if you see the output of my code, when I change the country from the select item it actually display's the corresponding level in other select item "level". But, my problem is that unless/until, I change the select item from "level" input,I am not getting the value of it after submitting the form. Not, sure if I am doing something wrong there or just the form itself doesn't work like that.

**Comment by iamandrewluca** [comment]
I don't know exactly if this is a bug, but better to provide initial values, when  you don't have a default `<option/>`

This is what I did.

```jsx
import React from "react";
import { Field, reduxForm, formValueSelector } from "redux-form";
import { useSelector } from "react-redux";

// create a form selector
const formSelect = formValueSelector('simple')

// extract items outside form
const items = [
  { country: "USA", level: 1 },
  { country: "Canada", level: 2 },
  { country: "Bangladesh", level: 7 }
];

const AddNewForm = props => {
  const { handleSubmit, pristine, reset, submitting } = props;

  // get a real reference to selected item in store
  const selected = useSelector(state => formSelect(state, 'country'))

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>First Name</label>
        <div>
          <Field
            name="firstName"
            component="input"
            type="text"
            placeholder="First Name"
          />
        </div>
      </div>
      <div>
        <label>Country</label>
        <div>
		  // onChange is not needed
          <Field name="country" component="select">
            {Array.from(new Set(items.map(item => item.country))).map(
              (country, index) => (
                <option key={country} selected={index === 0 ? true : undefined} value={country}>{country}</option>
              )
            )}
          </Field>
        </div>
      </div>
      <div>
        <label>Level</label>
        <div>
          <Field name="level" component="select">
            {items
              .filter(item => item.country === selected)
              .map((item, index) => (
                <option key={index} value={item.level}>{item.level}</option>
              ))}
          </Field>
        </div>
      </div>
      <div>
        <button type="submit" disabled={pristine || submitting}>
          Submit
        </button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>
          Clear Values
        </button>
      </div>
    </form>
  );
};

export default reduxForm({
  form: "simple", // a unique identifier for this form
  enableReinitialize: true,
  initialValues: {
	// because you don't have a default empty option,
	// better to provide visible selected option as a initial value
    country: items[0].country
  }
})(AddNewForm);
```

**Comment by mdsaon** [comment]
Yes, I understood correctly, it makes sense to provide initial value if we don't have default <option />. I am just wondering why the onSubmit doesn't get values from the "level" selection even though it is changing the values on country selection. Somehow, it just accepts that we at least manually change the value from the "level" field once...

**Comment by mdsaon** [comment]
passed also initial value for "level" but always getting the output like this:
{country: "USA", level: 1, firstName: "df"}
{country: "Bangladesh", level: 1, firstName: "df"}
 {country: "USA", level: 1, firstName: "df"}
Even though it is changing the level value in the UI

**Comment by iamandrewluca** [comment]
Your level should also have a initial value, and it seems there is no point in level select, because you filtering to show only selected.

**Comment by mdsaon** [comment]
yes,I have tried after passing the initial value to the level as well like you have passed for country:
export default reduxForm({
  form: "simple", // a unique identifier for this form
  enableReinitialize: true,
  initialValues: {
	// because you don't have a default empty option,
	// better to provide visible selected option as a initial value
    country: items[0].country,
    level:items[0].level
  }
})(NewForm);
But,seems no luck yet

**Comment by mdsaon** [comment]
The level get the initial value passed all the times even though it renders different value on country selection

**Comment by iamandrewluca** [comment]
Because you change options at each render.

Try to remove `.filter(item => item.country === selected)`

I'll close this because is more a support question. Feel free to continue the discussion.
