### ISSUE TITLE
FieldArray name [Object object error]

### ISSUE THREAD

**Issue by dancixx** [redux-form/redux-form#4650]
Hi guys,

if i submit the form, i have an issue in response json.
```<FieldArray name={`exercises.${item}.exerciseSets`} component={renderSets}  />```
The `item` is an array, but give back an undefined `[Object object]` error.

![image](https://user-images.githubusercontent.com/56868953/78818064-5b4caa00-79d4-11ea-868c-60099f19957f.png)

Do i write something wrong or redux-form cant handle this?

**Comment by iamandrewluca** [comment]
@dancixx if `item` is an object this
```
exercises.${item}.exerciseSets
```
will be interpolated like this
```
exercises.[Object object].exerciseSets
```
You're setting name in a wrong way.

**Comment by dancixx** [comment]
@iamandrewluca thanks for answer. So this way isnt any solution simply hook the object data?

**Comment by iamandrewluca** [comment]
I don't understand exactly what you want to do. I'm mostly sure you are using `FieldArray` in a wrong way.

https://github.com/redux-form/redux-form/blob/master/.github/support.md

**Comment by dancixx** [comment]
@iamandrewluca 
https://stackoverflow.com/questions/61105330/redux-form-firebase-original-fields-push
