### ISSUE TITLE
Redux form text input changes the browser theme-color on type

### ISSUE THREAD

**Issue by Shariaty** [redux-form/redux-form#4657]
### Redux form text input changes the browser theme-color on type

When typing into redux form text input, theme-color attribute resets to default, and there is no error and warning in the console.

### Your environment

- **OS**: Problem can be seen on Android - google chrome
- **Packages**: "react": "^16.13.1",  "redux-form": "^8.3.1"
### Video of the behavior

![Demo](https://user-images.githubusercontent.com/21170564/79049081-9ea65300-7c36-11ea-803b-541030232e09.gif)

**Comment by iamandrewluca** [comment]
Thats weird. Can you try also this with a simple input, without `redux-form`? `redux-form` does not have anything to do with the styling of the app.

**Comment by Shariaty** [comment]
@iamandrewluca Sorry, It was my bad not checking it before post the issue here. It is also happening with simple input. So I guess I should report it on react page instead of here.

**Comment by iamandrewluca** [comment]
Don't think is a react bug either, I think this may be a chrome issue.
