### ISSUE TITLE
Focus lost when Field's "component" prop provided a function

### ISSUE THREAD

**Issue by ArturBaybulatov** [redux-form/redux-form#4662]
### Subject of the issue

When a Fields's `component` prop provided an anonymous function, and when form's validation state changes, active field loses focus:

```js
{Object.values(fields).map(field => (
  <Field
    key={field.id}
    name={field.id}
    component={rf => (
      <field.widget label={field.title} rf={rf} />
    )}
  />
))}
```

I have to define it as a function, because my custom widget needs extra data from a `field` object.

Same trick works fine in react-final-form, but I can't use it, because I need my form state in redux.

### My environment

- **OS**: Windows 10
- **Packages**: Latest versions of all: react 16.13.1, react-dom 16.13.1, react-redux 7.2.0, redux 4.0.5, redux-form 8.3.5
- **Env**: Chrome 80

### Steps to reproduce

See the sandbox. Try typing and deleting a singe character in an input, and observe that focus has been lost:

https://codesandbox.io/s/redux-form-template-23b16?file=/MyForm.js:931-1002

### Expected behaviour

Focus not lost.

### Actual behaviour

Focus lost and a user can't proceed typing until manually focuses again.

**Comment by iamandrewluca** [comment]
> I have to define it as a function, because my custom widget needs extra data from a field object.

you can pass that data to `Field` directly it will be passed to component`

Change your fields to be like

```js
{Object.values(fields).map(field => (
  <Field
    key={field.id}
    name={field.id}
    label={field.title}
    component={field.widget}
  />
))}
```

And adapt your widgets this way.

```js
const Input = ({ label, input, meta }) => (
  <div>
    <input label={label} onChange={input.onChange} value={input.value} />
    {meta.error && <span>{meta.error}</span>}
  </div>
);
```
