### ISSUE TITLE
Field array doesn't update

### ISSUE THREAD

**Issue by sandorvasas** [redux-form/redux-form#4665]
v6.8.0
rerenderOnEveryChange is true.

I have a field array of objects, initially configured with emptry string fields. There are 2 objects in the array, and each item has a radio button, first one is checked.
Radio buttons act like exclusive checkboxes, so they have a boolean value instead of a string.
Their onChange event looks like:
```tsx
render() {
  return (
    /* .... */
    <RadioButtonField
      label="Primary"
      input={{
        value: this.fp.formData.values.fields.diagnosis[i].primaryDiagnosisIndicator,
        onChange: checked => checked && this.handleChangePrimaryDiagnosisIndicator(i)
      }}
    />
    /* .... */
  )
}

/* .... */

handleChangePrimaryDiagnosisIndicator(diagnosisIndex: number) {
  for (let i = 0; i < this.fp.formData.values.fields.diagnosis.length; ++i) {
    this.fp.changeFieldValue(
      `fields.diagnosis[${i}].primaryDiagnosisIndicator`,
      i == diagnosisIndex
    )
  }
}
```
So the first one is selected intially, and when I click the second, the above dispatches two change events: `fields.diagnosis[0].primaryDiagnosisIndicator: false` and `fields.diagnosis[1].primaryDiagnosisIndicator: true`, but the FieldArray doesn't re-render. It only re-renders if I change any of the string fields. Then the radio buttons display the correct state.

So my guess is when other fields are empty, boolean value changes do update the redux store but they don't t trigger a re-render of the field array.

**Comment by sandorvasas** [comment]
Nvm. Updated to 7.1.1 and that seems to have fixed it. Can't update to 8.x because it crashes all of our forms (40+).

**Comment by iamandrewluca** [comment]
I'd suggest to keep it on v7 some time, and with time you'll se what's needed for v8 upgrade. I am new collaborator on redux-form, and don't know what exactly changed between v6 -> v7 -> v8
