### ISSUE TITLE
Material-UI AutoComplete Required attribute Issue

### ISSUE THREAD

**Issue by JitendraBhamidipati** [redux-form/redux-form#4670]
### Subject of the issue
With Material UI Autocomplete I cant able to give the field as required to show error.

### Steps to reproduce

Here is the  sandbox [link](https://codesandbox.io/s/frosty-pine-9xdih?file=/src/form.jsx). Try with and without adding the inputs field to TextField you can see the issue. 

When Inputs passed to TextField
1. If you select a value and click outside the field. value disappears but the value is stored
2. If you touch and click outside error is occured 

![ac-1](https://user-images.githubusercontent.com/31988265/80712309-6eecbb80-8b0f-11ea-83f9-f58ed336376f.JPG)

When Inputs are not passed to TextField
1. If you touch and click outside it should show error. 
2. If you select a value and click outside the field. value is visible.

![ac-2](https://user-images.githubusercontent.com/31988265/80712315-701de880-8b0f-11ea-8640-520afd139fc0.JPG)

### Expected behaviour

The field Value should be present when you click outside the field.
If the field is touched and clicked outside It should show error

**Comment by iamandrewluca** [comment]
The problem is that `touched` is always false. This is because `touched` is set when `input.onFocus` is triggered, in your case you ignore this event.

**Comment by JitendraBhamidipati** [comment]
@iamandrewluca  adding OnBlur event to Textfield will remove the selected item when we click outside.

**Comment by iamandrewluca** [comment]
Don't know exactly, but I think you should pass `onBlur` to `Autocomplete`, not `TextField`

https://redux-form.com/8.3.0/docs/api/field.md/#-code-input-onblur-eventorvalue-function-code-

**Comment by JitendraBhamidipati** [comment]
Autocomplete doesnt have onBlur function.

**Comment by JitendraBhamidipati** [comment]
@iamandrewluca please reopen the issue.Adding the onblur to autocomplete also not working. Autocomplete indirectly uses textfield component.

**Comment by iamandrewluca** [comment]
Try tris on `TextField` `onBlur={values => input.onBlur(values)}`

**Comment by iamandrewluca** [comment]
@JitendraBhamidipati what the problem? As I said this is not a redux-form issue. You are not using redux-form the right way. If you pas `input.onBlur` to `TextField` everything works fine as you stated

> The field Value should be present when you click outside the field.
> If the field is touched and clicked outside It should show error

**Comment by JitendraBhamidipati** [comment]
@iamandrewluca I have updated the sandboxlink. Added the onBlur to TextField. It is not working. I am able to get error when i touch it and drop off, but when i select a value and click outside the field the data is not visible on the field.

**Comment by iamandrewluca** [comment]
Change the onBlur this way.
onBlur={() => input.onBlur(input.value)}

**Comment by JitendraBhamidipati** [comment]
@iamandrewluca  I have added blurOnSelect to autocomplete and then even after selecting the value I am seeing the error. After selecting not going into required validation. And also If possible a example on this field would be better as it is being commonly used these days.

**Comment by JitendraBhamidipati** [comment]
Added these 2 lines for Autocomplete 
` blurOnSelect
        onClose={() => input.onBlur()}` 
and removed this line in TextField worked for me.
`onBlur={() => input.onBlur(input.value)}`.

**Comment by iamandrewluca** [comment]
Would be great if you could put an example using `Autocomplete`. We are few contributors and cannot handle all use cases. Thanks.

**Comment by JitendraBhamidipati** [comment]
@iamandrewluca I want to work on this issue but when I forked the repository I see there is no example code. Even in redux-form webpage examples is missing. v8.3.0
