### ISSUE TITLE
handleSubmit fires cached version when form is submited by dispatch

### ISSUE THREAD

**Issue by ideffix** [redux-form/redux-form#4682]
### Subject of the issue
It looks like submit by `<button type='submit' />` and `dispatch(submit('form'))` behaves differently. While submiting by button is ok, submiting using dispatch fires cached function (first function that is passed to `handleSubmit` function)

### Your environment

| Software              | Version(s) |
| --------------------- | ---------- |
| `redux-form`          | 8.3.6 
| `redux`               | 4.0.5
| `react-redux`         | 7.2.0
| `react`               | 16.12.0
| `react-dom`           | 16.12.0

### Steps to reproduce

https://codesandbox.io/s/ecstatic-leftpad-54u9k
Fill any data in form, click `Submit` - it should log in console your data. Now try `Submit by dispatch` - it logs `undefined`.

### Expected behaviour

Submit by button and dispatch should fire the same function passed to handleSubmit.

### Actual behaviour

Submit by dispatch fires cached function.

**Comment by iamandrewluca** [comment]
I don't think this is a issue.
From the code that is provided, developer cached the data from the store before submit.
Code is doing exactly what you tell him to do.
You provide to `handleSubmit` a function that already extracted the data from the store.

**Comment by ideffix** [comment]
I've modifed code and now on every render `logData()` is called. Everytime when `useSelector` from `useData` hook return new data, new function is returned. Passed function `logData` to `handleSubmit` is the same for button `submit` and for manually dispatch. My question is: why submitting with button have other result than submitting with `dispatch` ?

**Comment by erikras** [comment]
Published fix in [`v8.3.7`](https://github.com/redux-form/redux-form/releases/tag/v8.3.7).
