### ISSUE TITLE
Showing input before clicking the add button

### ISSUE THREAD

**Issue by nurcinozer** [redux-form/redux-form#4719]
I tried this tutorial: [https://redux-form.com/6.1.1/examples/fieldarrays/](https://redux-form.com/6.1.1/examples/fieldarrays/) but I want to show "first name" and "last name" inputs before clicking the "add member" button. I mean, when the page is first opened, the two inputs will already be shown and the user will press the button whenever the user wants to add extra input. how can I do that?

**Comment by diesttro** [comment]
You need to put those first values of `FieldArray` into initialValues property, so those first values will be rendered.

**Comment by nurcinozer** [comment]
@diesttro I did, but when I want to go back and edit the inputs, the inputs are empty this time even when i set enableReinitialize: true

**Comment by diesttro** [comment]
It's strange to go back and edit a form. Anyways once you go back it will be mounted again with its initial values. Without code example I can only recommend you to check your redux state and dispatched actions.
