### ISSUE TITLE
Validations function for <Fields> no working

### ISSUE THREAD

**Issue by tombrowndev** [redux-form/redux-form#4724]
### Validations function for `<Fields>` no working

Validation functions defined outside of the component do not work the same when used within a `<Fields />` component vs with `<Field />`.

Works: (Pseudo)
```
const ComponentA = () => {
  return <Fields component={MyFields} names={["name"]} />;
}

const MyFields = () => {
  return <Input validate={(value) => value ? null : "Required" } />;
}
```

Does not work: (Pseudo)
```
import { validations } from "./utils";

const ComponentA = () => {
  return <Fields component={MyFields} names={["name"]} />;
}

const MyFields = () => {
  return <Field validate={validations.required} />;
}
```

For now, I am fixing this by using bind like: (Pseudo)
```
import { validations } from "./utils";

const ComponentA = () => {
  return <Fields component={MyFields} names={["name"]} />;
}

const MyFields = () => {
  return <Field validate={validations.required.bind(this)} />;
}
```

CodeSandbox: https://codesandbox.io/s/empty-violet-8f06c?file=/src/App.js

### Your environment

| Software              | Version(s) |
| --------------------- | ---------- |
| `redux-form`          | v8.3.7
| `redux`               | v4.0.5
| `react-redux`         | v7.2.3
| `react`               | v16.13.1
| `react-dom`           | v16.13.1
| `node`                | v12.14.2
| `npm` if using        | 
| `yarn` if using       | 
| `flow` if using       | 
| `typescript` if using | 
| Browser               | Chrome v89
| Operating System      | Mac

**Comment by tombrowndev** [comment]
Is this a bug, or is it to be expected. If it's expected, is binding this the correct approach to resolving it?

**Comment by tombrown-ibm** [comment]
Seems like this could be related in some way to #4017 4017

**Comment by tombrowndev** [comment]
Re-looking at this, I believe that `Field` should not be used with `Fields`, and that validation should also be done at the `Fields` level.

Closing this issue.
